name=SimcomA76xx
version=0.1.1
author=Péter Soós
maintainer=Péter Soós
sentence=A library for SimCom A76xx series LTE modems.
paragraph=Designed for stability on ESP32 and Arduino, focusing on network band management, signal quality, and reliable AT command parsing.
category=Communication
url=https://github.com/soosp/SimcomA76xx
architectures=*
